### ISSUE TITLE
Request to switch from rhino.github.io > rhino3d.github.io for redirects to grasshopper.com, to free up github.com/rhino

### ISSUE THREAD

**Issue by p-bakker** [rhino3d/rhino3d.github.io#1]
Hi @rhino @robinrodricks

I'm contacting you on behalve of the [Rhino](https://github.com/Mozilla/rhino) project: we really like to use the rhino.github.com user/organization to host repo's related to our Rhino project.

However, rhino.github.com is currently (only) in use for redirecting traffic from rhino.github.io towards grasshopper.com.

I don't know the historical reason for the aforementioned redirects, but I'm hoping its either not surving a purpose anymore or that it would be (relatively) straight-forward to instead have the redirects go through rhino3d.github.io, which I set up in this organization & repo.

Would really appreciate if you could look into this and consider exchanging the rhino user/organization with me/us for the rhino3d organization I've set up (for you).

Eagerly awaiting your response,

Paul

Note: I tried contacting @robinrodricks directly via email, but no response so far. Maybe I've got the wrong email address

**Comment by p-bakker** [comment]
If you're open to this idea, but worried about any links out there to rhino.github.io/components/* or rhino.github.io/addons/*  breaking, we could see if we can somehow keep those redirects working

**Comment by dan-rigdon-bel** [comment]
Hi @p-bakker -

I'm writing here on behalf of (this other) [Rhino](https://www.rhino3d.com/).  I can understand why you would like to use this user/organization.  In our case, that was our desire when we reached out to @robinrodericks, given that his site was directly related to the software we develop.

Currently, http://rhino.github.io/ continues to serve our users well.  We also have the intention to move more of our GitHub presence from our current: https://github.com/mcneel/ to https://github.com/rhino/ as we continue to open-source more parts of our software.  The timeline for this is TBD, but we reached out to Robin with this concern a few years back - not to mention the issues that arise with control of [our trademarks](https://www.rhino3d.com/mcneel/trademarks/).

Anyway, that's all background: I see you've set up: https://github.com/rhino3d/
We will have to consider that.  Hopefully, I can get back to you soon.

Best,
-Dan

**Comment by p-bakker** [comment]
Hi @dan-rigdon-bel, tnx for reaching out

> Currently, http://rhino.github.io/ continues to serve our users well

Wondering how exactly: afaics the only place where the rhino.github.io url is actually used is in a few posts on your discourse, see https://discourse.mcneel.com/search?q=rhino.github.io: no more references to rhino.github.io after the [annourcement of grasshopperdocs.com](https://discourse.mcneel.com/t/announcement-new-and-improved-grasshopper-docs-website/96318/9).

AFAICS rhino.github.io only serves to provide redirects to the (new) grasshopperdocs.com website for the legacy urls in some of these old posts

Anyways, looking forward to hearing back from you

**Comment by p-bakker** [comment]
The swap has been made, so closing this issue
